algoritmo "Exercício3"
// 
// Descrição   : Ler um número e exibir o dobro
// Autor(a)    : Lucas Batista
// Data atual  : 03/08/2026
var
// Seção de Declarações das variáveis 
   numero, dobro: inteiro

inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite um numero: ")
   leia(numero)
   dobro <- numero*2
   escreval("Você digitou o número: ",numero,".")
   escreval(" O dobro de ", numero, " é: ", dobro,".")

fimalgoritmo