algoritmo "Aula 3. Exercício4"
//  
// Descrição   : Calcula a Área do Triângulo
// Autor(a)    : Lucas Batista
// Data atual  : 03/08/2026
Var
// Seção de Declarações das variáveis 
   area, base, altura: real

inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    escreval("Informe a Base do Triângulo: ")
    leia(base)

    escreval("Informe a Altura do Triângulo: ")
    leia(altura)

    area <- (base*altura)/2
    escreva("A área do Triângulo é: ",area,".")

fimalgoritmo