algoritmo "Exercicio13"
//
//
// Descricao   : Exibe os pares entre 1 e 100
// Autor(a)    : Lucas Batista
// Data atual  : 03/08/2026
var
// Secao de Declaracoes das variaveis
  i, n: inteiro

inicio
// Serao de Comandos, procedimento, funcoes, operadores, etc...
 //recebe um numero inteiro N
   escreval("A lista a seguir mostra todos os números pares entre 1 e 100")
   n <- 100
   i <- 1
 //o contador incrementa até N
   enquanto i <= n faca
   i <- i+1
 //verifica se o resto da divisão de N por 2 é = 0
   se i mod 2 = 0 entao
   escreval(i, " é PAR")
   fimse
   fimenquanto



fimalgoritmo