algoritmo "Exercício4"
//  
// Descrição   : pode dirigir: ler a idade do usuário e informar se pode dirigir ou não
// Autor(a)    : Lucas Batista
// Data atual  : 03/08/2026
var
// Seção de Declarações das variáveis 
   idade: inteiro
   
inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreva("Digite sua idade: ")
   leia(idade)
   
   se idade >= 18 entao
    escreva("Pode dirigir")
   senao
    escreval("Não pode dirigir")
   fimse
    

fimalgoritmo