algoritmo "Exercicio14"
//
//
// Descricao   : Soma de todos os número até N
// Autor(a)    : Lucas Batista
// Data atual  : 03/08/2026
var
// Secao de Declaracoes das variaveis
  i, n, soma: inteiro

inicio
// Serao de Comandos, procedimento, funcoes, operadores, etc...
 //recebe um numero inteiro N
   escreval("Insira um numero inteiro: ")
   leia(n)
   
  // i <- 1
 //o contador incrementa até N
   enquanto i <= n faca
  //soma recebe os numeros do contador
   soma <- soma + i
   i <- i+1
   fimenquanto

 //exibi a soma de 1 a N
   escreval(" A soma dos numero de 1 a", n," é: ", soma)





fimalgoritmo