algoritmo "Exercício5"
//
//
// Descrição   : Informar se um número é positivo ou negativo
// Autor(a)    : Lucas Batista
// Data atual  : 03/08/2026
var
// Seção de Declarações das variáveis
   numero: inteiro

inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   escreva("Informe um número: ")
   leia(numero)

   se numero > 0 entao
    escreva("O ", numero," é positivo")
  fimse
   se numero < 0 entao
    escreva("O ", numero," é negativo")
  fimse
   se numero = 0 entao
    escreva("O zero é neutro")
  fimse
    

fimalgoritmo