algoritmo "Aula 3. Exercicio1"
// 
// Descrição   : Dobro e o Triplo de um número
// Autor(a)    : Lucas Batista
// Data atual  : 03/08/2026
Var
// Seção de Declarações das variáveis 
   numero, dobro, triplo: inteiro


inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um número: ")
   leia(numero)
   escreval("Você digitou: ",numero)
   dobro <- numero*2
   triplo <- numero*3
   escreval("O Dobro de ", numero," é: ",dobro,".")
   escreval("O Triplo de ", numero," é: ",triplo,".")
   

fimalgoritmo