algoritmo "Exercicio12"
//
//
// Descricao   : Conta de 10 a 1 e exibe "FELIZ ANO NOVO!!!"
// Autor(a)    : Lucas Batista
// Data atual  : 03/08/2026
var
// Secao de Declaracoes das variaveis
  i: inteiro

inicio
// Serao de Comandos, procedimento, funcoes, operadores, etc...
   i <- 10
    //quando o contador exibe i até chegar em i = 1.
   enquanto i >= 1  faca
   escreval(i)
   i <- i-1
   fimenquanto
   //fim do contador. Exibe FELIZ ANO NOVO!!!
   escreval("FELIZ ANO NOVO!!!")



fimalgoritmo